# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import tableProjection_pb2 as tableProjection__pb2


class TableProjectionStub(object):
    """The greeting service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.FindTableProjection = channel.unary_unary(
                '/greet.TableProjection/FindTableProjection',
                request_serializer=tableProjection__pb2.TableProjectionRequest.SerializeToString,
                response_deserializer=tableProjection__pb2.TableProjectionReply.FromString,
                )


class TableProjectionServicer(object):
    """The greeting service definition.
    """

    def FindTableProjection(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TableProjectionServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'FindTableProjection': grpc.unary_unary_rpc_method_handler(
                    servicer.FindTableProjection,
                    request_deserializer=tableProjection__pb2.TableProjectionRequest.FromString,
                    response_serializer=tableProjection__pb2.TableProjectionReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'greet.TableProjection', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class TableProjection(object):
    """The greeting service definition.
    """

    @staticmethod
    def FindTableProjection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/greet.TableProjection/FindTableProjection',
            tableProjection__pb2.TableProjectionRequest.SerializeToString,
            tableProjection__pb2.TableProjectionReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
