# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tableProjection.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='tableProjection.proto',
  package='greet',
  syntax='proto3',
  serialized_options=b'\252\002\013GrpcService',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x15tableProjection.proto\x12\x05greet\"W\n\x16TableProjectionRequest\x12\x14\n\x0c\x64\x61tabaseName\x18\x01 \x01(\t\x12\x11\n\ttableName\x18\x02 \x01(\t\x12\x14\n\x0c\x63olumnsNames\x18\x03 \x03(\t\"y\n\x14TableProjectionReply\x12\x37\n\x0eprojectionRows\x18\x01 \x03(\x0b\x32\x1f.greet.TableProjectionReply.Row\x12\x14\n\x0c\x45rrorMessage\x18\x02 \x01(\t\x1a\x12\n\x03Row\x12\x0b\n\x03row\x18\x01 \x03(\t2d\n\x0fTableProjection\x12Q\n\x13\x46indTableProjection\x12\x1d.greet.TableProjectionRequest\x1a\x1b.greet.TableProjectionReplyB\x0e\xaa\x02\x0bGrpcServiceb\x06proto3'
)




_TABLEPROJECTIONREQUEST = _descriptor.Descriptor(
  name='TableProjectionRequest',
  full_name='greet.TableProjectionRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='databaseName', full_name='greet.TableProjectionRequest.databaseName', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='tableName', full_name='greet.TableProjectionRequest.tableName', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='columnsNames', full_name='greet.TableProjectionRequest.columnsNames', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=119,
)


_TABLEPROJECTIONREPLY_ROW = _descriptor.Descriptor(
  name='Row',
  full_name='greet.TableProjectionReply.Row',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='row', full_name='greet.TableProjectionReply.Row.row', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=224,
  serialized_end=242,
)

_TABLEPROJECTIONREPLY = _descriptor.Descriptor(
  name='TableProjectionReply',
  full_name='greet.TableProjectionReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='projectionRows', full_name='greet.TableProjectionReply.projectionRows', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ErrorMessage', full_name='greet.TableProjectionReply.ErrorMessage', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_TABLEPROJECTIONREPLY_ROW, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=121,
  serialized_end=242,
)

_TABLEPROJECTIONREPLY_ROW.containing_type = _TABLEPROJECTIONREPLY
_TABLEPROJECTIONREPLY.fields_by_name['projectionRows'].message_type = _TABLEPROJECTIONREPLY_ROW
DESCRIPTOR.message_types_by_name['TableProjectionRequest'] = _TABLEPROJECTIONREQUEST
DESCRIPTOR.message_types_by_name['TableProjectionReply'] = _TABLEPROJECTIONREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TableProjectionRequest = _reflection.GeneratedProtocolMessageType('TableProjectionRequest', (_message.Message,), {
  'DESCRIPTOR' : _TABLEPROJECTIONREQUEST,
  '__module__' : 'tableProjection_pb2'
  # @@protoc_insertion_point(class_scope:greet.TableProjectionRequest)
  })
_sym_db.RegisterMessage(TableProjectionRequest)

TableProjectionReply = _reflection.GeneratedProtocolMessageType('TableProjectionReply', (_message.Message,), {

  'Row' : _reflection.GeneratedProtocolMessageType('Row', (_message.Message,), {
    'DESCRIPTOR' : _TABLEPROJECTIONREPLY_ROW,
    '__module__' : 'tableProjection_pb2'
    # @@protoc_insertion_point(class_scope:greet.TableProjectionReply.Row)
    })
  ,
  'DESCRIPTOR' : _TABLEPROJECTIONREPLY,
  '__module__' : 'tableProjection_pb2'
  # @@protoc_insertion_point(class_scope:greet.TableProjectionReply)
  })
_sym_db.RegisterMessage(TableProjectionReply)
_sym_db.RegisterMessage(TableProjectionReply.Row)


DESCRIPTOR._options = None

_TABLEPROJECTION = _descriptor.ServiceDescriptor(
  name='TableProjection',
  full_name='greet.TableProjection',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=244,
  serialized_end=344,
  methods=[
  _descriptor.MethodDescriptor(
    name='FindTableProjection',
    full_name='greet.TableProjection.FindTableProjection',
    index=0,
    containing_service=None,
    input_type=_TABLEPROJECTIONREQUEST,
    output_type=_TABLEPROJECTIONREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_TABLEPROJECTION)

DESCRIPTOR.services_by_name['TableProjection'] = _TABLEPROJECTION

# @@protoc_insertion_point(module_scope)
